
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Attachment
 * 
 */
export type Attachment = Prisma.AttachmentModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model ConversationParticipant
 * 
 */
export type ConversationParticipant = Prisma.ConversationParticipantModel
/**
 * Model FriendRequest
 * 
 */
export type FriendRequest = Prisma.FriendRequestModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model PasswordReset
 * 
 */
export type PasswordReset = Prisma.PasswordResetModel
/**
 * Model Reaction
 * 
 */
export type Reaction = Prisma.ReactionModel
/**
 * Model ReadReceipt
 * 
 */
export type ReadReceipt = Prisma.ReadReceiptModel
/**
 * Model TokenBlacklist
 * 
 */
export type TokenBlacklist = Prisma.TokenBlacklistModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
