
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `AuthChallenge` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AuthChallenge
 * Single-use challenge tokens for 2FA setup / verify / recovery.
 */
export type AuthChallengeModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthChallengePayload>

export type AggregateAuthChallenge = {
  _count: AuthChallengeCountAggregateOutputType | null
  _min: AuthChallengeMinAggregateOutputType | null
  _max: AuthChallengeMaxAggregateOutputType | null
}

export type AuthChallengeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  email: string | null
  type: string | null
  totpSecretEnc: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type AuthChallengeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  email: string | null
  type: string | null
  totpSecretEnc: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type AuthChallengeCountAggregateOutputType = {
  id: number
  userId: number
  email: number
  type: number
  totpSecretEnc: number
  expiresAt: number
  usedAt: number
  createdAt: number
  _all: number
}


export type AuthChallengeMinAggregateInputType = {
  id?: true
  userId?: true
  email?: true
  type?: true
  totpSecretEnc?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type AuthChallengeMaxAggregateInputType = {
  id?: true
  userId?: true
  email?: true
  type?: true
  totpSecretEnc?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type AuthChallengeCountAggregateInputType = {
  id?: true
  userId?: true
  email?: true
  type?: true
  totpSecretEnc?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
  _all?: true
}

export type AuthChallengeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthChallenge to aggregate.
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AuthChallenges to fetch.
   */
  orderBy?: Prisma.AuthChallengeOrderByWithRelationInput | Prisma.AuthChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.AuthChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AuthChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AuthChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned AuthChallenges
  **/
  _count?: true | AuthChallengeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
  **/
  _min?: AuthChallengeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
  **/
  _max?: AuthChallengeMaxAggregateInputType
}

export type GetAuthChallengeAggregateType<T extends AuthChallengeAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthChallenge]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthChallenge[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthChallenge[P]>
}




export type AuthChallengeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthChallengeWhereInput
  orderBy?: Prisma.AuthChallengeOrderByWithAggregationInput | Prisma.AuthChallengeOrderByWithAggregationInput[]
  by: Prisma.AuthChallengeScalarFieldEnum[] | Prisma.AuthChallengeScalarFieldEnum
  having?: Prisma.AuthChallengeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthChallengeCountAggregateInputType | true
  _min?: AuthChallengeMinAggregateInputType
  _max?: AuthChallengeMaxAggregateInputType
}

export type AuthChallengeGroupByOutputType = {
  id: string
  userId: string
  email: string
  type: string
  totpSecretEnc: string | null
  expiresAt: Date
  usedAt: Date | null
  createdAt: Date
  _count: AuthChallengeCountAggregateOutputType | null
  _min: AuthChallengeMinAggregateOutputType | null
  _max: AuthChallengeMaxAggregateOutputType | null
}

export type GetAuthChallengeGroupByPayload<T extends AuthChallengeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthChallengeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthChallengeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthChallengeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthChallengeGroupByOutputType[P]>
      }
    >
  >



export type AuthChallengeWhereInput = {
  AND?: Prisma.AuthChallengeWhereInput | Prisma.AuthChallengeWhereInput[]
  OR?: Prisma.AuthChallengeWhereInput[]
  NOT?: Prisma.AuthChallengeWhereInput | Prisma.AuthChallengeWhereInput[]
  id?: Prisma.StringFilter<"AuthChallenge"> | string
  userId?: Prisma.StringFilter<"AuthChallenge"> | string
  email?: Prisma.StringFilter<"AuthChallenge"> | string
  type?: Prisma.StringFilter<"AuthChallenge"> | string
  totpSecretEnc?: Prisma.StringNullableFilter<"AuthChallenge"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"AuthChallenge"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"AuthChallenge"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AuthChallenge"> | Date | string
}

export type AuthChallengeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  type?: Prisma.SortOrder
  totpSecretEnc?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthChallengeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuthChallengeWhereInput | Prisma.AuthChallengeWhereInput[]
  OR?: Prisma.AuthChallengeWhereInput[]
  NOT?: Prisma.AuthChallengeWhereInput | Prisma.AuthChallengeWhereInput[]
  userId?: Prisma.StringFilter<"AuthChallenge"> | string
  email?: Prisma.StringFilter<"AuthChallenge"> | string
  type?: Prisma.StringFilter<"AuthChallenge"> | string
  totpSecretEnc?: Prisma.StringNullableFilter<"AuthChallenge"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"AuthChallenge"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"AuthChallenge"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AuthChallenge"> | Date | string
}, "id">

export type AuthChallengeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  type?: Prisma.SortOrder
  totpSecretEnc?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AuthChallengeCountOrderByAggregateInput
  _max?: Prisma.AuthChallengeMaxOrderByAggregateInput
  _min?: Prisma.AuthChallengeMinOrderByAggregateInput
}

export type AuthChallengeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthChallengeScalarWhereWithAggregatesInput | Prisma.AuthChallengeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthChallengeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthChallengeScalarWhereWithAggregatesInput | Prisma.AuthChallengeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthChallenge"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AuthChallenge"> | string
  email?: Prisma.StringWithAggregatesFilter<"AuthChallenge"> | string
  type?: Prisma.StringWithAggregatesFilter<"AuthChallenge"> | string
  totpSecretEnc?: Prisma.StringNullableWithAggregatesFilter<"AuthChallenge"> | string | null
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"AuthChallenge"> | Date | string
  usedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AuthChallenge"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AuthChallenge"> | Date | string
}

export type AuthChallengeCreateInput = {
  id: string
  userId: string
  email: string
  type: string
  totpSecretEnc?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type AuthChallengeUncheckedCreateInput = {
  id: string
  userId: string
  email: string
  type: string
  totpSecretEnc?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type AuthChallengeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  totpSecretEnc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthChallengeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  totpSecretEnc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthChallengeCreateManyInput = {
  id: string
  userId: string
  email: string
  type: string
  totpSecretEnc?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type AuthChallengeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  totpSecretEnc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthChallengeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  totpSecretEnc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthChallengeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  type?: Prisma.SortOrder
  totpSecretEnc?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthChallengeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  type?: Prisma.SortOrder
  totpSecretEnc?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthChallengeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  type?: Prisma.SortOrder
  totpSecretEnc?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type AuthChallengeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  email?: boolean
  type?: boolean
  totpSecretEnc?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["authChallenge"]>

export type AuthChallengeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  email?: boolean
  type?: boolean
  totpSecretEnc?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["authChallenge"]>

export type AuthChallengeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  email?: boolean
  type?: boolean
  totpSecretEnc?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["authChallenge"]>

export type AuthChallengeSelectScalar = {
  id?: boolean
  userId?: boolean
  email?: boolean
  type?: boolean
  totpSecretEnc?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}

export type AuthChallengeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "email" | "type" | "totpSecretEnc" | "expiresAt" | "usedAt" | "createdAt", ExtArgs["result"]["authChallenge"]>

export type $AuthChallengePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthChallenge"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    email: string
    type: string
    totpSecretEnc: string | null
    expiresAt: Date
    usedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["authChallenge"]>
  composites: {}
}

export type AuthChallengeGetPayload<S extends boolean | null | undefined | AuthChallengeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload, S>

export type AuthChallengeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthChallengeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: AuthChallengeCountAggregateInputType | true
  }

export interface AuthChallengeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthChallenge'], meta: { name: 'AuthChallenge' } }
  /**
   * Find zero or one AuthChallenge that matches the filter.
   * @param {AuthChallengeFindUniqueArgs} args - Arguments to find a AuthChallenge
   * @example
   * // Get one AuthChallenge
   * const authChallenge = await prisma.authChallenge.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthChallengeFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthChallengeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthChallenge that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthChallengeFindUniqueOrThrowArgs} args - Arguments to find a AuthChallenge
   * @example
   * // Get one AuthChallenge
   * const authChallenge = await prisma.authChallenge.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthChallengeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthChallengeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthChallenge that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeFindFirstArgs} args - Arguments to find a AuthChallenge
   * @example
   * // Get one AuthChallenge
   * const authChallenge = await prisma.authChallenge.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthChallengeFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthChallengeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthChallenge that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeFindFirstOrThrowArgs} args - Arguments to find a AuthChallenge
   * @example
   * // Get one AuthChallenge
   * const authChallenge = await prisma.authChallenge.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthChallengeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthChallengeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthChallenges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthChallenges
   * const authChallenges = await prisma.authChallenge.findMany()
   *
   * // Get first 10 AuthChallenges
   * const authChallenges = await prisma.authChallenge.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const authChallengeWithIdOnly = await prisma.authChallenge.findMany({ select: { id: true } })
   *
   */
  findMany<T extends AuthChallengeFindManyArgs>(args?: Prisma.SelectSubset<T, AuthChallengeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthChallenge.
   * @param {AuthChallengeCreateArgs} args - Arguments to create a AuthChallenge.
   * @example
   * // Create one AuthChallenge
   * const AuthChallenge = await prisma.authChallenge.create({
   *   data: {
   *     // ... data to create a AuthChallenge
   *   }
   * })
   *
   */
  create<T extends AuthChallengeCreateArgs>(args: Prisma.SelectSubset<T, AuthChallengeCreateArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthChallenges.
   * @param {AuthChallengeCreateManyArgs} args - Arguments to create many AuthChallenges.
   * @example
   * // Create many AuthChallenges
   * const authChallenge = await prisma.authChallenge.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends AuthChallengeCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthChallengeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthChallenges and returns the data saved in the database.
   * @param {AuthChallengeCreateManyAndReturnArgs} args - Arguments to create many AuthChallenges.
   * @example
   * // Create many AuthChallenges
   * const authChallenge = await prisma.authChallenge.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many AuthChallenges and only return the `id`
   * const authChallengeWithIdOnly = await prisma.authChallenge.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends AuthChallengeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthChallengeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthChallenge.
   * @param {AuthChallengeDeleteArgs} args - Arguments to delete one AuthChallenge.
   * @example
   * // Delete one AuthChallenge
   * const AuthChallenge = await prisma.authChallenge.delete({
   *   where: {
   *     // ... filter to delete one AuthChallenge
   *   }
   * })
   *
   */
  delete<T extends AuthChallengeDeleteArgs>(args: Prisma.SelectSubset<T, AuthChallengeDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthChallenge.
   * @param {AuthChallengeUpdateArgs} args - Arguments to update one AuthChallenge.
   * @example
   * // Update one AuthChallenge
   * const authChallenge = await prisma.authChallenge.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends AuthChallengeUpdateArgs>(args: Prisma.SelectSubset<T, AuthChallengeUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthChallenges.
   * @param {AuthChallengeDeleteManyArgs} args - Arguments to filter AuthChallenges to delete.
   * @example
   * // Delete a few AuthChallenges
   * const { count } = await prisma.authChallenge.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends AuthChallengeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthChallengeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthChallenges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthChallenges
   * const authChallenge = await prisma.authChallenge.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends AuthChallengeUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthChallengeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthChallenges and returns the data updated in the database.
   * @param {AuthChallengeUpdateManyAndReturnArgs} args - Arguments to update many AuthChallenges.
   * @example
   * // Update many AuthChallenges
   * const authChallenge = await prisma.authChallenge.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more AuthChallenges and only return the `id`
   * const authChallengeWithIdOnly = await prisma.authChallenge.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends AuthChallengeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthChallengeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthChallenge.
   * @param {AuthChallengeUpsertArgs} args - Arguments to update or create a AuthChallenge.
   * @example
   * // Update or create a AuthChallenge
   * const authChallenge = await prisma.authChallenge.upsert({
   *   create: {
   *     // ... data to create a AuthChallenge
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthChallenge we want to update
   *   }
   * })
   */
  upsert<T extends AuthChallengeUpsertArgs>(args: Prisma.SelectSubset<T, AuthChallengeUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthChallengePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthChallenges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeCountArgs} args - Arguments to filter AuthChallenges to count.
   * @example
   * // Count the number of AuthChallenges
   * const count = await prisma.authChallenge.count({
   *   where: {
   *     // ... the filter for the AuthChallenges we want to count
   *   }
   * })
  **/
  count<T extends AuthChallengeCountArgs>(
    args?: Prisma.Subset<T, AuthChallengeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthChallengeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthChallenge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthChallengeAggregateArgs>(args: Prisma.Subset<T, AuthChallengeAggregateArgs>): Prisma.PrismaPromise<GetAuthChallengeAggregateType<T>>

  /**
   * Group by AuthChallenge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthChallengeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
  **/
  groupBy<
    T extends AuthChallengeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthChallengeGroupByArgs['orderBy'] }
      : { orderBy?: AuthChallengeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthChallengeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthChallengeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthChallenge model
 */
readonly fields: AuthChallengeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthChallenge.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthChallengeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthChallenge model
 */
export interface AuthChallengeFieldRefs {
  readonly id: Prisma.FieldRef<"AuthChallenge", 'String'>
  readonly userId: Prisma.FieldRef<"AuthChallenge", 'String'>
  readonly email: Prisma.FieldRef<"AuthChallenge", 'String'>
  readonly type: Prisma.FieldRef<"AuthChallenge", 'String'>
  readonly totpSecretEnc: Prisma.FieldRef<"AuthChallenge", 'String'>
  readonly expiresAt: Prisma.FieldRef<"AuthChallenge", 'DateTime'>
  readonly usedAt: Prisma.FieldRef<"AuthChallenge", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AuthChallenge", 'DateTime'>
}


// Custom InputTypes
/**
 * AuthChallenge findUnique
 */
export type AuthChallengeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter, which AuthChallenge to fetch.
   */
  where: Prisma.AuthChallengeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge findUniqueOrThrow
 */
export type AuthChallengeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter, which AuthChallenge to fetch.
   */
  where: Prisma.AuthChallengeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge findFirst
 */
export type AuthChallengeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter, which AuthChallenge to fetch.
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AuthChallenges to fetch.
   */
  orderBy?: Prisma.AuthChallengeOrderByWithRelationInput | Prisma.AuthChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AuthChallenges.
   */
  cursor?: Prisma.AuthChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AuthChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AuthChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AuthChallenges.
   */
  distinct?: Prisma.AuthChallengeScalarFieldEnum | Prisma.AuthChallengeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge findFirstOrThrow
 */
export type AuthChallengeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter, which AuthChallenge to fetch.
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AuthChallenges to fetch.
   */
  orderBy?: Prisma.AuthChallengeOrderByWithRelationInput | Prisma.AuthChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AuthChallenges.
   */
  cursor?: Prisma.AuthChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AuthChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AuthChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AuthChallenges.
   */
  distinct?: Prisma.AuthChallengeScalarFieldEnum | Prisma.AuthChallengeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge findMany
 */
export type AuthChallengeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter, which AuthChallenges to fetch.
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AuthChallenges to fetch.
   */
  orderBy?: Prisma.AuthChallengeOrderByWithRelationInput | Prisma.AuthChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing AuthChallenges.
   */
  cursor?: Prisma.AuthChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AuthChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AuthChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AuthChallenges.
   */
  distinct?: Prisma.AuthChallengeScalarFieldEnum | Prisma.AuthChallengeScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge create
 */
export type AuthChallengeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * The data needed to create a AuthChallenge.
   */
  data: Prisma.XOR<Prisma.AuthChallengeCreateInput, Prisma.AuthChallengeUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge createMany
 */
export type AuthChallengeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthChallenges.
   */
  data: Prisma.AuthChallengeCreateManyInput | Prisma.AuthChallengeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthChallenge createManyAndReturn
 */
export type AuthChallengeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * The data used to create many AuthChallenges.
   */
  data: Prisma.AuthChallengeCreateManyInput | Prisma.AuthChallengeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthChallenge update
 */
export type AuthChallengeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * The data needed to update a AuthChallenge.
   */
  data: Prisma.XOR<Prisma.AuthChallengeUpdateInput, Prisma.AuthChallengeUncheckedUpdateInput>
  /**
   * Choose, which AuthChallenge to update.
   */
  where: Prisma.AuthChallengeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge updateMany
 */
export type AuthChallengeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthChallenges.
   */
  data: Prisma.XOR<Prisma.AuthChallengeUpdateManyMutationInput, Prisma.AuthChallengeUncheckedUpdateManyInput>
  /**
   * Filter which AuthChallenges to update
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * Limit how many AuthChallenges to update.
   */
  limit?: number
}

/**
 * AuthChallenge updateManyAndReturn
 */
export type AuthChallengeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * The data used to update AuthChallenges.
   */
  data: Prisma.XOR<Prisma.AuthChallengeUpdateManyMutationInput, Prisma.AuthChallengeUncheckedUpdateManyInput>
  /**
   * Filter which AuthChallenges to update
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * Limit how many AuthChallenges to update.
   */
  limit?: number
}

/**
 * AuthChallenge upsert
 */
export type AuthChallengeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * The filter to search for the AuthChallenge to update in case it exists.
   */
  where: Prisma.AuthChallengeWhereUniqueInput
  /**
   * In case the AuthChallenge found by the `where` argument doesn't exist, create a new AuthChallenge with this data.
   */
  create: Prisma.XOR<Prisma.AuthChallengeCreateInput, Prisma.AuthChallengeUncheckedCreateInput>
  /**
   * In case the AuthChallenge was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthChallengeUpdateInput, Prisma.AuthChallengeUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge delete
 */
export type AuthChallengeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
  /**
   * Filter which AuthChallenge to delete.
   */
  where: Prisma.AuthChallengeWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuthChallenge deleteMany
 */
export type AuthChallengeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthChallenges to delete
   */
  where?: Prisma.AuthChallengeWhereInput
  /**
   * Limit how many AuthChallenges to delete.
   */
  limit?: number
}

/**
 * AuthChallenge without action
 */
export type AuthChallengeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthChallenge
   */
  select?: Prisma.AuthChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthChallenge
   */
  omit?: Prisma.AuthChallengeOmit<ExtArgs> | null
}
