name: Trigger Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook to deploy
        run: |
          curl -X POST https://profiles.uside.studio/deploy \
            -H "Content-Type: application/json" \
            -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_TOKEN }}" \
            -d '{
              "trigger": "github",
              "DATABASE_URL": "${{ secrets.DATABASE_URL }}",
              "JWT_SECRET": "${{ secrets.JWT_SECRET }}",
              "JWT_REFRESH_SECRET": "${{ secrets.JWT_REFRESH_SECRET }}",
              "APP_URL": "${{ secrets.APP_URL }}",
              "REDIS_URL": "${{ secrets.REDIS_URL }}",
              "REDIS_KEY_PREFIX": "bcn:profiles:",
              "EMAIL_USER": "${{ secrets.EMAIL_USER }}",
              "EMAIL_PASSWORD": "${{ secrets.EMAIL_PASSWORD }}"
            }'
